// <auto-generated />
// This attribute is used by the CommandRegistrationGenerator

namespace Slack.Infrastructure;

/// <summary>
/// Marks a command class for automatic registration.
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AutoRegisterCommandAttribute : Attribute
{
    /// <summary>
    /// Registration order. Lower values are registered first.
    /// Use higher values (e.g., int.MaxValue) for commands that depend on the registry.
    /// </summary>
    public int Order { get; set; } = 0;
}
