using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Slack.Generators;

[Generator]
public class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeName = "AutoRegisterCommand";
    private const string AttributeFullName = "Slack.Infrastructure.AutoRegisterCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 查找所有标记了 [AutoRegisterCommand] 的类
        var commandClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetCommandInfo(ctx))
            .Where(static m => m is not null);

        // 收集所有命令信息
        var collected = commandClasses.Collect();

        // 生成代码
        context.RegisterSourceOutput(collected, static (spc, commands) =>
        {
            var source = GenerateExtensionClass(commands!);
            spc.AddSource("CommandRegistryExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl &&
               classDecl.AttributeLists.Count > 0;
    }

    private static CommandInfo? GetCommandInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        // 查找 AutoRegisterCommand 属性
        var attribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == AttributeName ||
                                 a.AttributeClass?.Name == AttributeName + "Attribute");

        if (attribute is null)
            return null;

        // 检查是否实现了 ICommand 接口
        var implementsICommand = symbol.AllInterfaces
            .Any(i => i.Name == "ICommand");

        if (!implementsICommand)
            return null;

        // 获取 Order 属性值
        var order = 0;
        foreach (var namedArg in attribute.NamedArguments)
        {
            if (namedArg.Key == "Order" && namedArg.Value.Value is int orderValue)
            {
                order = orderValue;
            }
        }

        // 检查是否需要 CommandRegistry 构造函数参数
        var needsRegistry = symbol.Constructors
            .Any(c => c.Parameters.Any(p => p.Type.Name == "CommandRegistry"));

        return new CommandInfo(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            order,
            needsRegistry);
    }

    private static string GenerateExtensionClass(ImmutableArray<CommandInfo?> commands)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Slack.Commands;");
        sb.AppendLine("using Slack.Infrastructure;");
        sb.AppendLine();
        sb.AppendLine("namespace Slack.Infrastructure;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated extension methods for command registration.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class CommandRegistryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all commands marked with [AutoRegisterCommand].");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void RegisterAllCommands(this CommandRegistry registry)");
        sb.AppendLine("    {");

        // 按 Order 排序
        var sortedCommands = commands
            .Where(c => c is not null)
            .OrderBy(c => c!.Order)
            .ThenBy(c => c!.ClassName)
            .ToList();

        foreach (var cmd in sortedCommands)
        {
            if (cmd is null) continue;

            if (cmd.NeedsRegistry)
            {
                sb.AppendLine($"        registry.Register(new {cmd.ClassName}(registry));");
            }
            else
            {
                sb.AppendLine($"        registry.Register(new {cmd.ClassName}());");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class CommandInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public int Order { get; }
        public bool NeedsRegistry { get; }

        public CommandInfo(string ns, string className, int order, bool needsRegistry)
        {
            Namespace = ns;
            ClassName = className;
            Order = order;
            NeedsRegistry = needsRegistry;
        }
    }
}
