using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Slack.Generators;

[Generator]
public class I18nGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 获取所有 .json 文件
        var jsonFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".json") && file.Path.Contains("locales"));

        // 收集所有 JSON 文件内容
        var jsonContents = jsonFiles.Select((file, cancellationToken) =>
        {
            var text = file.GetText(cancellationToken)?.ToString() ?? "{}";
            var fileName = Path.GetFileNameWithoutExtension(file.Path);
            return new JsonFileInfo(fileName, text);
        }).Collect();

        // 生成代码
        context.RegisterSourceOutput(jsonContents, (spc, files) =>
        {
            if (!files.Any()) return;

            var filesList = files.ToList();
            
            // 找到默认语言文件 (en.json)
            var defaultFile = filesList.FirstOrDefault(f => f.FileName == "en");
            if (defaultFile == null)
            {
                defaultFile = filesList.First();
            }

            // 解析所有语言的键值对
            var allLocales = new Dictionary<string, Dictionary<string, string>>();
            foreach (var file in filesList)
            {
                allLocales[file.FileName] = ParseJson(file.Content);
            }

            // 生成代码
            var source = GenerateStringsClass(allLocales, defaultFile.FileName);
            spc.AddSource("Strings.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static Dictionary<string, string> ParseJson(string json)
    {
        var result = new Dictionary<string, string>();
        
        // 简单的 JSON 解析（不使用 System.Text.Json 以保持 netstandard2.0 兼容）
        var matches = Regex.Matches(json, @"""([^""]+)""\s*:\s*""([^""]*(?:\\.[^""]*)*)""");
        foreach (Match match in matches)
        {
            var key = match.Groups[1].Value;
            var value = match.Groups[2].Value
                .Replace("\\n", "\n")
                .Replace("\\\"", "\"")
                .Replace("\\\\", "\\");
            result[key] = value;
        }
        
        return result;
    }

    private static string GenerateStringsClass(Dictionary<string, Dictionary<string, string>> allLocales, string defaultLocale)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Slack.Localization;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated localization strings");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class Strings");
        sb.AppendLine("{");
        
        // 获取所有键
        var allKeys = allLocales.Values
            .SelectMany(d => d.Keys)
            .Distinct()
            .OrderBy(k => k);

        foreach (var key in allKeys)
        {
            var propertyName = ToPascalCase(key);
            
            sb.AppendLine("    /// <summary>");
            Dictionary<string, string> defaultDict;
            string defaultValue;
            if (allLocales.TryGetValue(defaultLocale, out defaultDict) && defaultDict.TryGetValue(key, out defaultValue))
            {
                sb.AppendLine($"    /// {EscapeXmlComment(defaultValue)}");
            }
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static string {propertyName} => CurrentLocale switch");
            sb.AppendLine("    {");
            
            foreach (var kvp in allLocales.OrderBy(x => x.Key))
            {
                var locale = kvp.Key;
                var dict = kvp.Value;
                string value;
                if (dict.TryGetValue(key, out value))
                {
                    var escapedValue = EscapeString(value);
                    if (locale == "zh-CN")
                    {
                        sb.AppendLine($"        var l when l.StartsWith(\"zh\") => \"{escapedValue}\",");
                    }
                    else if (locale == "en")
                    {
                        // 英文作为默认
                    }
                    else
                    {
                        sb.AppendLine($"        \"{locale}\" => \"{escapedValue}\",");
                    }
                }
            }
            
            // 默认值
            Dictionary<string, string> enDict;
            string enValue;
            if (allLocales.TryGetValue("en", out enDict) && enDict.TryGetValue(key, out enValue))
            {
                sb.AppendLine($"        _ => \"{EscapeString(enValue)}\"");
            }
            else
            {
                Dictionary<string, string> defDict;
                string defValue;
                if (allLocales.TryGetValue(defaultLocale, out defDict) && defDict.TryGetValue(key, out defValue))
                {
                    sb.AppendLine($"        _ => \"{EscapeString(defValue)}\"");
                }
                else
                {
                    sb.AppendLine($"        _ => \"{key}\"");
                }
            }
            
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        
        var words = input.Split('_', '-', '.');
        var result = new StringBuilder();
        foreach (var word in words)
        {
            if (word.Length > 0)
            {
                result.Append(char.ToUpper(word[0]));
                if (word.Length > 1)
                {
                    result.Append(word.Substring(1));
                }
            }
        }
        return result.ToString();
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string EscapeXmlComment(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\n", " ")
            .Replace("\r", "");
    }

    private class JsonFileInfo
    {
        public string FileName { get; }
        public string Content { get; }

        public JsonFileInfo(string fileName, string content)
        {
            FileName = fileName;
            Content = content;
        }
    }
}
